# vim:set ft=tmux:
%hidden MODULE_NAME="git_branch"

set -g "@catppuccin_${MODULE_NAME}_icon" "󰘬 "
set -gF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_green}"
set -g "@catppuccin_${MODULE_NAME}_text" " #(/home/razvan/.config/tmux/scripts/git-branch \"#{pane_current_path}\")"

source "/home/razvan/.local/share/tmux/plugins/tmux/utils/status_module.conf"
