# zsh entrypoint
source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/env.zsh"
source "$XDG_CONFIG_HOME/zsh/paths.zsh"
source "$XDG_CONFIG_HOME/zsh/oh-my-zsh.zsh"
source "$XDG_CONFIG_HOME/zsh/aliases.zsh"

source "$ZSH/oh-my-zsh.sh"

source "$XDG_CONFIG_HOME/zsh/tools.zsh"
